-- Update industry fields in deals table
-- Generated from reparse_result.json

UPDATE deals SET industry = 'Quantum/DX' WHERE company_name = 'SDT';
UPDATE deals SET industry = 'Proptech/AI' WHERE company_name = '에디트콜렉티브';
UPDATE deals SET industry = 'Quantum/DX' WHERE company_name = 'SDT';
UPDATE deals SET industry = 'Mobility/Logistics' WHERE company_name = 'KRG그룹';
UPDATE deals SET industry = 'Medical Device/Aesthetics' WHERE company_name = '클래시스';
UPDATE deals SET industry = 'O2O/Service' WHERE company_name = '열다컴퍼니';
UPDATE deals SET industry = 'Mobility Platform' WHERE company_name = '차봇 모빌리티';
UPDATE deals SET industry = 'Database/Infra' WHERE company_name = '타이디비';
UPDATE deals SET industry = 'Web3/Platform' WHERE company_name = 'Konnect';
UPDATE deals SET industry = '푸드테크' WHERE company_name = '웨이크';
UPDATE deals SET industry = 'Mobility/Used Car' WHERE company_name = '빅웨이브카';
UPDATE deals SET industry = '창업 지원' WHERE company_name = '미주한인창업자연합';
UPDATE deals SET industry = 'Social/Platform' WHERE company_name = '피키';
UPDATE deals SET industry = 'AI/OCR' WHERE company_name = '한국딥러닝';
UPDATE deals SET industry = '푸드테크' WHERE company_name = '포스페이스랩';
UPDATE deals SET industry = 'AI Semiconductor' WHERE company_name = '리벨리온';
UPDATE deals SET industry = '콘텐츠' WHERE company_name = '키뮤스튜디오';
UPDATE deals SET industry = 'AI Data Platform' WHERE company_name = '크라우드웍스';
UPDATE deals SET industry = 'Metaverse/SNS' WHERE company_name = '메타 플랫폼스';
UPDATE deals SET industry = 'IT/Software' WHERE company_name = '매니패스트';
UPDATE deals SET industry = 'Semiconductor Equipment' WHERE company_name = '아이에스티이';
UPDATE deals SET industry = 'Waste Management' WHERE company_name = '그린다';
UPDATE deals SET industry = 'Shared Office' WHERE company_name = '오피스허브';
UPDATE deals SET industry = 'Semiconductor IP' WHERE company_name = '탄탄코어';
UPDATE deals SET industry = 'Proptech/Data' WHERE company_name = '알스퀘어';
UPDATE deals SET industry = 'AgriTech/Smart Farm' WHERE company_name = '엘바';
UPDATE deals SET industry = 'IT' WHERE company_name = '콕스웨이브';
UPDATE deals SET industry = 'Accelerator/VC' WHERE company_name = '블루포인트파트너스';
UPDATE deals SET industry = 'Fintech' WHERE company_name = '넥스트파이낸스이니셔티브';
UPDATE deals SET industry = 'Proptech/Data' WHERE company_name = '밸류맵';
UPDATE deals SET industry = 'Pet Healthcare' WHERE company_name = '십일리터';
UPDATE deals SET industry = 'Fintech/AI' WHERE company_name = '뉴아이';
UPDATE deals SET industry = 'Loyalty Platform' WHERE company_name = '위드포인츠';
UPDATE deals SET industry = 'Food Tech' WHERE company_name = '퓨어스페이스';
UPDATE deals SET industry = 'Digital Healthcare' WHERE company_name = '휴이노';
UPDATE deals SET industry = 'Manufacturing/EMS' WHERE company_name = '인탑스';
UPDATE deals SET industry = 'Mobility/AI' WHERE company_name = '어메스';
UPDATE deals SET industry = 'VC/Accelerator' WHERE company_name = '뉴패러다임인베스트먼트';
UPDATE deals SET industry = 'Edutech' WHERE company_name = '아워스팟';
UPDATE deals SET industry = 'Fintech/Forex' WHERE company_name = '한패스';
UPDATE deals SET industry = 'AI/LLM' WHERE company_name = '올거나이즈';
UPDATE deals SET industry = 'Web3/Platform' WHERE company_name = '코넥트';
UPDATE deals SET industry = 'Legal Service' WHERE company_name = '법무법인 미션';
UPDATE deals SET industry = 'Accelerator' WHERE company_name = '세종창조경제혁신센터';
UPDATE deals SET industry = 'Display Materials' WHERE company_name = '아크리얼';
UPDATE deals SET industry = 'Crowdfunding' WHERE company_name = '와디즈임팩트';
UPDATE deals SET industry = '헬스케어' WHERE company_name = '리전 헬스';
UPDATE deals SET industry = '이커머스' WHERE company_name = '오비터스';
UPDATE deals SET industry = 'AI/Synthetic Data' WHERE company_name = '큐빅';
UPDATE deals SET industry = 'Crowdfunding/Platform' WHERE company_name = '와디즈';
UPDATE deals SET industry = 'Tax Tech' WHERE company_name = '자비스앤빌런즈';
UPDATE deals SET industry = 'Medical Device' WHERE company_name = '아셉틱';
UPDATE deals SET industry = 'Data Platform' WHERE company_name = '퍼슬리';
UPDATE deals SET industry = 'IT' WHERE company_name = '에스와이유';
UPDATE deals SET industry = 'Eco Tech' WHERE company_name = '워터베이션';
UPDATE deals SET industry = 'F&B' WHERE company_name = '주미당';
UPDATE deals SET industry = 'Game/Content' WHERE company_name = '긱스로프트';
UPDATE deals SET industry = 'O2O/Flower' WHERE company_name = '플로라운지';
UPDATE deals SET industry = 'Cloud/AI' WHERE company_name = '네이버클라우드';
UPDATE deals SET industry = '핀테크' WHERE company_name = '링크알파';
UPDATE deals SET industry = 'IT' WHERE company_name = '아이피텍';
UPDATE deals SET industry = 'Luxury Commerce' WHERE company_name = '바이버';
UPDATE deals SET industry = 'Cybersecurity' WHERE company_name = '로그프레소';